include:
  - ../_default/networks.yml

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=America/Sao_Paulo
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - overseerr-config:/app/config
    restart: unless-stopped
    networks:
      - internet

volumes:
  overseerr-config:
