include:
  - ../_default/networks.yml

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=104
      - PGID=105
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-appdata:/config
      - type: bind
        source: /var/lib/media_server/downloads/torrents
        target: /mnt/media/downloads/torrents
        bind:
          selinux: z
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - internet

volumes:
  qbittorrent-appdata:
