include:
  - ../_network/compose.yml

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - VIRTUAL_HOST=sonarr.CERBERUSNET.localdomain
      - VIRTUAL_PORT=8989
    volumes:
      - sonarr-data:/config
      - sonarr-tvseries:/tv #optional
      - sonarr-downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - private-media

volumes:
  sonarr-data:
  sonarr-tvseries:
  sonarr-downloads:
