include:
  - ../_default/networks.yml

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      TZ: America/Sao_Paulo
      FTLCONF_webserver_api_password: null
      WEBPASSWORD: null
      WEBPASSWORD_FILE: /run/secrets/pihole-pwd
      PIHOLE_UID: 106
      PIHOLE_GID: 107
    cap_add:
      - SYS_NICE
    volumes:
      - type: bind
        source: /mnt/ssd/pihole
        target: /etc/pihole
        bind:
          selinux: z
    restart: unless-stopped
    secrets:
      - pihole-pwd
    network_mode: host

secrets:
  pihole-pwd:
    file: ./secrets/pihole_pwd.txt
