include:
  - ../_default/networks.yml

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      TZ: America/Sao_Paulo
      WEBPASSWORD_FILE: /run/secrets/pihole-pwd
      PIHOLE_UID: 106
      PIHOLE_GID: 107
    volumes:
      - type: bind
        source: /var/lib/pihole
        target: /etc/pihole
        bind:
          selinux: z
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    secrets:
      - pihole-pwd
    networks:
      private-infra:
      internet:
        ipv4_address: '192.168.100.0'

secrets:
  pihole-pwd:
    file: ./secrets/pihole_pwd.txt
