include:
  - ../_default/networks.yml

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - private-infra
    depends_on:
      - nginx-pm
      - pihole

volumes:
  portainer-data:
